export const DRAG_DEPARTMENT = "DRAG_DEPARTMENT";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const DRAG_USER_IN_DEPARTMENT = "DRAG_USER_IN_DEPARTMENT";
export const GET_DEPARTMENT_DETAIL = "GET_DEPARTMENT_DETAIL";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const GET_USER_IN_DEPARTMENT = "GET_USER_IN_DEPARTMENT";
export const GET_USER_IN_DEPARTMENT_FAIL = "GET_USER_IN_DEPARTMENT_FAIL";

export const DRAG_PROJECT_GROUP = "DRAG_PROJECT_GROUP";

export const DRAG_USER = "DRAG_USER";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_USER_ALL = "GET_USER_ALL";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_ICON_SUCCESS = "ADD_ICON_SUCCESS";
export const GET_ICON_SUCCESS = "GET_ICON_SUCCESS";
export const SELECT_ICON = "SELECT_ICON";
export const DELETE_ICON = "DELETE_ICON";
